//Jeff Stein
//6th Period
//Mr. Baker
//Program:Song using Functions
#include <iostream.h>
#include <conio.h>
#include <apstring.h>
#include <iomanip.h>
#include <apvector.h>
#include <apmatrix.h>
#include <stdlib.h>

void vers1 ();
void vers2 ();
void vers3 ();
void vers4 ();
void vers5 ();
void vers6 ();
void chor ();
void ending ();

void main()
{
clrscr();

cout<<setw(40)<<"Turn the Page"<<endl;
cout<<setw(40)<<"by Metallica"<<endl;
vers1 ();
vers2 ();
chor ();
getch ();
clrscr ();
vers3 ();
vers4 ();
chor ();
getch ();
clrscr ();
vers5 ();
vers6 ();
ending ();






getch();
};

void vers1  ()
{
cout<<endl;
cout<<endl;
cout<<"On a long and lonesome highway east of Omaha "<<endl;
cout<<"You can listen to the engines moaning out as a one note song "<<endl;
cout<<"You think about the woman or the girl you knew the night before "<<endl;
}
void vers2 ()
{
cout<<endl;
cout<<endl;
cout<<"But your thoughts will soon be wandering the way they always do"<<endl;
cout<<"When your riding sixteen hours and there not much to do" <<endl;
cout<<"And you don't feel much like riding, you just wish the trip was through"<<endl;
}
void vers3 ()
{
cout<<endl;
cout<<endl;
cout<<"So you walk into this restaurant strung out from the road"<<endl;
cout<<"And you feel the eyes upon you, as you 're shaking off the cold"<<endl;
cout<<"You pretend it doesn't bother you, but you just want to explode"<<endl;
}
void vers4 ()
{
cout<<endl;
cout<<endl;
cout<<"Must times you can't hear'em talk, other times you can"<<endl;
cout<<"All the same cliches, 'Is it women?' 'Is it man?' "<<endl;
cout<<"And you always seemed out number, and don't dare to make a stand"<<endl;
cout<<"Make your stand"<<endl;
}
void vers5 ()
{
cout<<endl;
cout<<endl;
cout<<"Ooh-ooh, out there in the spotlight, your're million miles away."<<endl;
cout<<"Every once of energy you try to give away "<<endl;
cout<<"As the sweat pours out your body, like music that you play, yeah "<<endl;
}
void vers6 ()
{
cout<<endl;
cout<<endl;
cout<<"Later in the evening, you lie awake in bed."<<endl;
cout<<"With the echoes of the ampfiliers ringing in your head"<<endl;
cout<<"You smoke the day's last cigarette, remembering what she said "<<endl;
cout<<"What she said"<<endl;
}
void chor()
{
cout<<endl;
cout<<endl;
cout<<"Here I am - on the road again"<<endl;
cout<<"There I am - up on the stage"<<endl;
cout<<"Here I go - playing the star again"<<endl;
cout<<"There I go - turn the page"<<endl;
}
void ending ()
{
cout<<endl;
cout<<endl;
cout<<"Here I am - on the road again"<<endl;
cout<<"There I am - up on the stage"<<endl;
cout<<"Here I go - playing the star again"<<endl;
cout<<"There I go - turn the page"<<endl;
cout<<"There I go - turn the page "<<endl;
cout<<"There I go, yeah yeah"<<endl;
cout<<"There I go, yeah yeah"<<endl;
cout<<"There I go, yeah"<<endl;
cout<<"There I go, yeah"<<endl;
cout<<"There I go, oo-oo-ooh"<<endl;
cout<<"There I go"<<endl;
cout<<"And I'm gone."<<endl;
}