// Mahmood Subhani
// Period 6
// Mr. Baker
// Program: Prob#01 10 examples of each operator


#include<Iostream.h>
#include<conio.h>n
#include<apstring.h>



void main ()
{
clrscr();


cout<<"1+1="<<1+1<<endl;
cout<<"13+8="<<13+8<<endl;
cout<<"2+5="<<2+5<<endl;
cout<<"7+13="<<7+13<<endl;
cout<<"12+2="<<12+2<<endl;
cout<<"3+9="<<3+9<<endl;
cout<<"4+6="<<4+6<<endl;
cout<<"5+2="<<5+2<<endl;
cout<<"12+4="<<12+4<<endl;
cout<<"245+235="<<245+235<<endl<<endl;


cout<<"Please press return to continue.";
getch();
clrscr();

cout<<"3-1="<<3-1<<endl;
cout<<"6-4="<<6-4<<endl;
cout<<"9-3="<<9-3<<endl;
cout<<"13-6="<<13-6<<endl;
cout<<"478569365896638564841-743078958970458970="<<478569365896638564841-743078958970458970<<endl;
cout<<"34-6="<<34-6<<endl;
cout<<"12-3="<<12-3<<endl;
cout<<"35-64="<<35-64<<endl;
cout<<"24-87="<<24-87<<endl;
cout<<"3-7="<<89-45<<endl<<endl;


cout<<"Please press return to continue.";
getch();


clrscr();
cout<<"1*1="<<1*1<<endl;
cout<<"4*6="<<4*6<<endl;
cout<<"3*6="<<3*6<<endl;
cout<<"9*4="<<9*4<<endl;
cout<<"5*7="<<5*7<<endl;
cout<<"2*8="<<2*8<<endl;
cout<<"856*897478="<<856*897478<<endl;
cout<<"7*2="<<7*2<<endl;
cout<<"8*6="<<8*6<<endl;
cout<<"3*9="<<3*9<<endl<<endl;

cout<<"Please press return to continue.";
getch();


clrscr();
cout<<"1/1="<<1/1<<endl;
cout<<"3/5="<<3/5<<endl;
cout<<"21/7="<<21/7<<endl;
cout<<"9/3="<<9/3<<endl;
cout<<"2/1="<<2/1<<endl;
cout<<"81/9="<<81/9<<endl;
cout<<"7867324327/49839632="<<7867324327/49839632<<endl;
cout<<"25/5="<<25/5<<endl;
cout<<"36/9="<<1/1<<endl;
cout<<"63/7="<<63/7<<endl<<endl;




cout<<"Please press return to continue.";
getch();
};