// Mahmood Subhani
// Period 6
// Mr. Baker
// Program: Prob#00 Name, Address, Phone


#include<Iostream.h>
#include<conio.h>n
#include<apstring.h>


apstring  name;
apstring address;
apstring phone;
apstring press_button;


void main ()
{
clrscr();

name="Mahmood Subhani";
address="1220 Ramsey Ct";
phone="(972) 390-8016";
press_button="Please press button to continue";


cout<< name<<endl;
cout<< address<<endl;
cout<< phone<<endl<<endl;
cout<< press_button;
getch();

};