//Mahmood Subhani
//Period 5
//Mr. Baker
//Program: Class grades and stuff

#include <iostream.h>
#include <conio.h>
#include <iomanip.h>
#include <apvector.h>
#include <apstring.h>

//CONSTANTS


//STRUCTS
struct students_rec
{
apstring Name;
apvector <int> Grades();


};

struct class_rec
{
apvector <students_rec> students();
int gradenum;
};

//PROTOTYPES
void getdata();
void showclass();

//VARIABLES


void main()
{






};

void getdata()
{



}

void showclass()
{



}