// Mahmood Subhani
// Period 6
// Mr. Baker
// Program: Prob#00 Name, Address, Phone


#include<Iostream.h>
#include<conio.h>n
#include<apstring.h>
#include<iomanip.h>
#include<apvector.h>

void refrain2 ();
void refrain1 ();
void chorus ();

void main ()  {
clrscr();







refrain1();
chorus();
refrain2();
chorus();
cout<<"What???";
getch();
/*
It's all about the Pentiums, baby
Uhh, uh-huh, yeah Uhh, uh-huh, yeah
its all about the Pentiums, baby
It's all about the Pentiums, baby
It's all about the Pentiums!
It's all about the Pentiums!
(Yeah!!)

What y'all wanna do?
Wanna be hackers? Code crackers? Slackers
Wastin' time with all the chatroom yakkers?
9 to 5, chillin' at Hewlett Packard?
Workin' at a desk with a dumb little placard?
Yeah, payin' the bills with my mad programming skills
Defraggin' my hard drive for thrills
I got me a hundred gigabytes of RAM
I never feed trolls and I don't read spam
Installed a T1 line in my house
Always at my PC, double-clickin' on my mizouse
Upgrade my system at least twice a day
I'm strictly plug-and-play, I ain't afraid of Y2K
I'm down with Bill Gates, I call him Money for short
I phone him up at home and I make him do my tech support
It's all about the Pentiums, what?
You gotta be the dumbest newbie I've ever seen
You've got white-out all over your screen
You think your Commodore 64 is really neato
hat kinda chip you got in there, a Dorito?
You're using a 286? Don't make me laugh
Your Windows boots up in what, a day and a half?
You could back up your whole hard drive on a floppy diskette
You're the biggest joke on the internet
Your database is a disaster
You're waxin' your modem tryin' to make it go faster
Hey fella, I bet you're still livin' in your parents' cellar
Downloadin' pictures of Sarah Michelle Gellar
And postin "Me too!" like some brain-dead AOL-er
I should do the world a favor and cap you like Old Yeller
You're just about as useless as jpegs to Helen Keller

It's all about the Pentiums!
It's all about the Pentiums!
It's all about the Pentiums!
It's all about the Pentiums!

Now, what y'all wanna do?
Wanna be hackers? Code crackers? Slackers
Wastin' time with all the chatroom yakkers?
9 to 5, chillin at Hewlett Packard?

Uh, uh, loggin' in now
Wanna run wit my crew, hah?
Rule cyberspace and crunch numbers like I do?
They call me the king of the spreadsheets
Got em all printed out on my bedsheets
My new computer's got the clocks, it rocks
But it was obsolete before I opened the box
You say you've had your desktop for over a week?
Throw that junk away, man, it's an antique!
Your laptop is a month old? Well, that's great
If you could use a nice, heavy paperweight
My digital media is write-protected
Every file inspected, no viruses detected
I beta tested every operating system
Gave props to some, and others? I dissed 'em
While your computer's crashin', mine's multitaskin'
It does all my work without me even askin'
Got a flat-screen monitor, 40" wide
I believe that yours says "Etch-A-Sketch" on the side
In a 32-bit world, you're a 2-bit user
You've got your own newsgroup, alt.total-loser
Your mother board melts when you try to send a fax
Where'd you get your CPU, in a box of Cracker Jacks?
Play me online? Well, you know that I'll beat you
If I ever meet you I'll control-alt-delete you
What?

It's all about the Pentiums!
It's all about the Pentiums!
It's all about the Pentiums!
It's all about the Pentiums!
What y'all wanna do?
Wanna be hackers? Code crackers? Slackers
Wastin' time with all the chatroom yakkers?
9 to 5, chillin' at Hewlett Packard?
What??
*/

getch();

};

void chorus()
{

cout<<"It's all about the Pentiums!"<<endl<<
"It's all about the Pentiums!"<<endl<<
"It's all about the Pentiums!"<<endl<<
"It's all about the Pentiums!"<<endl<<endl<<

"Now, what y'all wanna do?"<<endl<<
"Wanna be hackers? Code crackers? Slackers"<<endl<<
"Wastin' time with all the chatroom yakkers?"<<endl<<
"9 to 5, chillin at Hewlett Packard?"<<endl;
getch();



};



void refrain1()

{

cout<<"It's all about the Pentiums, baby"<<endl<<
			 "Uhh, uh-huh, yeah Uhh, uh-huh, yeah"<<endl<<
			 "its all about the Pentiums, baby"<<endl<<
			 "It's all about the Pentiums, baby"<<endl<<
			 "It's all about the Pentiums!"<<endl<<
			 "It's all about the Pentiums!"<<endl<<
			 "(Yeah!!)"<<endl<<endl;

cout<<"What y'all wanna do?"<<endl<<
"Wanna be hackers? Code crackers? Slackers"<<endl<<
"Wastin' time with all the chatroom yakkers?"<<endl<<
"9 to 5, chillin' at Hewlett Packard?"<<endl<<
"Workin' at a desk with a dumb little placard?"<<endl<<
"Yeah, payin' the bills with my mad programming skills"<<endl<<
"Defraggin' my hard drive for thrills"<<endl<<
"I got me a hundred gigabytes of RAM"<<endl<<
"I never feed trolls and I don't read spam"<<endl<<
"Installed a T1 line in my house"<<endl<<
"Always at my PC, double-clickin' on my mizouse"<<endl<<
"Upgrade my system at least twice a day"<<endl<<
"I'm strictly plug-and-play, I ain't afraid of Y2K"<<endl<<
"I'm down with Bill Gates, I call him Money for short"<<endl<<
"I phone him up at home and I make him do my tech support"<<endl<<
"It's all about the Pentiums, what?"<<endl;

getch();
clrscr();

cout<<"You gotta be the dumbest newbie I've ever seen"<<endl<<
"You've got white-out all over your screen"<<endl<<
"You think your Commodore 64 is really neato"<<endl<<
"hat kinda chip you got in there, a Dorito?"<<endl<<
"You're using a 286? Don't make me laugh"<<endl<<
"Your Windows boots up in what, a day and a half?"<<endl<<
"You could back up your whole hard drive on a floppy diskette"<<endl<<
"You're the biggest joke on the internet"<<endl;
getch();
cout<<"Your database is a disaster"<<endl<<
"You're waxin' your modem tryin' to make it go faster"<<endl<<
"Hey fella, I bet you're still livin' in your parents' cellar"<<endl<<
"Downloadin' pictures of Sarah Michelle Gellar"<<endl<<
"And postin "<<"Me too!"<<"like some brain-dead AOL-er"<<endl<<
"I should do the world a favor and cap you like Old Yeller"<<endl<<
"You're just about as useless as jpegs to Helen Keller"<<endl<<endl;
getch();
};

void refrain2()

{
getch();
clrscr();
cout<<endl<<"Uh, uh, loggin' in now"<<endl<<
"Wanna run wit my crew, hah?"<<endl<<
"Rule cyberspace and crunch numbers like I do?"<<endl<<
"They call me the king of the spreadsheets"<<endl<<
"Got em all printed out on my bedsheets"<<endl<<
"My new computer's got the clocks, it rocks"<<endl<<
"But it was obsolete before I opened the box"<<endl<<
"You say you've had your desktop for over a week?"<<endl<<
"Throw that junk away, man, it's an antique!"<<endl<<
"Your laptop is a month old? Well, that's great"<<endl<<
"If you could use a nice, heavy paperweight"<<endl<<
"My digital media is write-protected"<<endl<<
"Every file inspected, no viruses detected"<<endl<<
"I beta tested every operating system"<<endl<<
"Gave props to some, and others? I dissed 'em"<<endl<<
"While your computer's crashin', mine's multitaskin'"<<endl<<
"It does all my work without me even askin'"<<endl;

getch();

cout<<"Got a flat-screen monitor, 40 inches wide"<<endl<<
"I believe that yours says Etch-A-Sketch on the side"<<endl<<
"In a 32-bit world, you're a 2-bit user"<<endl<<
"You've got your own newsgroup, alt.total-loser"<<endl<<
"Your mother board melts when you try to send a fax"<<endl<<
"Where'd you get your CPU, in a box of Cracker Jacks?"<<endl<<
"Play me online? Well, you know that I'll beat you"<<endl<<
"If I ever meet you I'll control-alt-delete you"<<endl<<
"What?"<<endl<<endl;

};
