//Jeremy Higgins
//August 24, 2001
//Mr. Baker
//Block 1
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//const
const int A=1;
const int B=2;
const	int C=3;
const	int D=4;
const	int E=5;
const	int F=6;
const	int G=7;
const	int H=8;
const	int I=9;
const	int J=10;
const	int K=11;
const	int L=12;
const	int M=13;
const	int N=14;
const	int O=15;
const int P=16;
const int Q=17;
const int R=18;
const int S=19;
const int T=20;
//var
void main()
{
clrscr();
cout<<"1+1="<<A+A<<endl<<"1+2="<<A+B<<endl<<"1+3="<<A+C<<endl;
cout<<"1+4="<<A+D<<endl<<"1+5="<<A+E<<endl<<"1+6="<<A+F<<endl;
cout<<"1+7="<<A+G<<endl<<"1+8="<<A+H<<endl<<"1+9="<<A+I<<endl;
cout<<"1+10="<<A+J<<endl;
getch();
clrscr();
cout<<"10-9="<<J-I<<endl<<"10-8="<<J-H<<endl<<"10-7="<<J-G<<endl;
cout<<"10-6="<<J-F<<endl<<"10-5="<<J-E<<endl<<"10-4="<<J-D<<endl;
cout<<"10-3="<<J-C<<endl<<"10-2="<<J-B<<endl<<"10-1="<<J-A<<endl;
cout<<"10-10="<<J-J<<endl;
getch();
clrscr();
cout<<"9*10="<<I*J<<endl<<"9*9="<<I*I<<endl<<"9*8="<<I*H<<endl;
cout<<"9*7="<<I*G<<endl<<"9*6="<<I*F<<endl<<"9*5="<<I*E<<endl;
cout<<"9*4="<<I*D<<endl<<"9*3="<<I*C<<endl<<"9*2="<<I*B<<endl;
cout<<"9*1="<<I*A<<endl;
getch();
clrscr();
cout<<"20/2="<<T/B<<endl<<"18/2="<<S/B<<endl<<"16/2="<<P/B<<endl;
cout<<"14/2="<<N/B<<endl<<"12/2="<<L/B<<endl<<"10/2="<<J/B<<endl;
cout<<"8/2="<<H/B<<endl<<"6/2="<<F/B<<endl<<"4/2="<<D/B<<endl;
cout<<"2/2="<<B/B<<endl;
getch();
clrscr();
cout<<"20%19="<<T%S<<endl<<"20%18="<<T%R<<endl<<"20%17="<<T%Q<<endl;
cout<<"20%16="<<T%P<<endl<<"20%15="<<T%O<<endl<<"20%14="<<T%N<<endl;
cout<<"20%13="<<T%M<<endl<<"20%12="<<T%L<<endl<<"20%11="<<T%K<<endl;
cout<<"20%9="<<T%I<<endl;
getch();
}
