// Sean Murray
// Due Date
// Stuff
// Mr. Baker - 3rd pd.

// Libraries
#include <conio.h>
#include <iostream.h>
#include <iomanip.h>
#include <apstring.h>

//Constants
const apstring NAME = "Sean Murray";
const apstring ADDRESS = "812 Carolyn";
const apstring NUMBER = "(972)727-0875";

//Variables

void main ()

{
	clrscr();
	cout<<endl<<NAME<<endl;
	cout<<ADDRESS<<endl;
	cout<<NUMBER<<endl;
	cout<<endl<<"Press return to continue.";
	getch();
}