// Sean Murray
// Due Date
// Program
// Mr. Baker - 3rd pd.

// Libraries
#include <conio.h>
#include <iostream.h>
#include <iomanip.h>
#include <apstring.h>
//Constants

//Variables

int Z = 0;

void main ()
{
clrscr();

cout <<Z + 4<<" + 5" " = "<<4 + 5<<endl;
cout <<Z + 10<<" + 10" " = "<<10 + 10<<endl;
cout <<Z + 2<<" + 2" " = "<<2 + 2<<endl;
cout <<Z + 5<<" + 5" " = "<<5 + 5<<endl;
cout <<Z + 1<<" + 1" " = "<<1 + 1<<endl;
cout <<Z + 8<<" + 8" " = "<<8 +8<<endl;
cout <<Z + 25<<" + 25" " = "<<25 + 25<<endl;
cout <<Z + 50<<" + 50" " = "<<50 + 50<<endl;
cout <<Z + 60<<" + 30" " = "<<60 + 30<<endl;
cout <<Z + 30<<" + 30" " = "<<30 + 30<<endl;

getch();
clrscr();

cout <<Z + 9<<" - 7 = "<<9 - 7<<endl;
cout <<Z + 5<<" - 4 = "<<5 - 4<<endl;
cout <<Z + 3<<" - 4 = "<<3 - 4<<endl;
cout <<Z + 2<<" - 1 = "<<2 - 1<<endl;
cout <<Z + 10<<" - 9 = "<<10 - 9<<endl;
cout <<Z + 25<<" - 30 = "<<25 - 30<<endl;
cout <<Z + 12<<" - 6 = "<<12 - 6<<endl;
cout <<Z + 4<<" - 18 = "<<4 - 18<<endl;
cout <<Z + 15<<" - 5 = "<<15 - 5<<endl;
cout <<Z + 22<<" - 11 = "<<22 - 11<<endl;

getch();
clrscr();

cout <<Z + 5<<" * 5 = "<<5 * 5<<endl;
cout <<Z + 4<<" * 4 = "<<4 * 4<<endl;
cout <<Z + 3<<" * 2 = "<<3 * 2<<endl;
cout <<Z + 2<<" * 2 = "<<2 * 2<<endl;
cout <<Z + 25<<" * 6 = "<<25 * 6<<endl;
cout <<Z + 25<<" * 12 = "<<12 * 12<<endl;
cout <<Z + 15<<" * 4 = "<<15 * 4<<endl;
cout <<Z + 4<<" * 25 = "<<4 * 25<<endl;
cout <<Z + 2<<" * 5 = "<<2 * 5<<endl;
cout <<Z + 4<<" * 12 = "<<4 * 12<<endl;

getch();
clrscr();

cout <<Z + 5<<" / 3 = "<<5 / 3<<endl;
cout <<Z + 8<<" / 4 = "<<8 / 4<<endl;
cout <<Z + 6<<" / 3 = "<<6 / 3<<endl;
cout <<Z + 8<<" / 1 = "<<8 / 1<<endl;
cout <<Z + 10<<" / 3 = "<<10 / 3<<endl;
cout <<Z + 5<<" / 1 = "<<5 / 1<<endl;
cout <<Z + 7<<" / 3 = "<<7 / 3<<endl;
cout <<Z + 4<<" / 4 = "<<4 / 4<<endl;
cout <<Z + 1<<" / 3 = "<<1 / 3<<endl;
cout <<Z + 7<<" / 3 = "<<7 / 3<<endl;
cout <<Z + 3<<" / 2 = "<<3 / 2<<endl;

getch();
clrscr();

cout <<Z + 1<<" % 10 = "<<1 % 10<<endl;
cout <<Z + 2<<" % 9 = "<<2 % 9<<endl;
cout <<Z + 3<<" % 8 = "<<3 % 8<<endl;
cout <<Z + 4<<" % 7 = "<<4 % 7<<endl;
cout <<Z + 5<<" % 6 = "<<5 % 6<<endl;
cout <<Z + 6<<" % 5 = "<<6 % 5<<endl;
cout <<Z + 7<<" % 4 = "<<7 % 4<<endl;
cout <<Z + 8<<" % 3 = "<<8 % 3<<endl;
cout <<Z + 9<<" % 2 = "<<9 % 2<<endl;
cout <<Z + 10<<" % 1 = "<<10 % 1<<endl;
getch();
}