//Comment
//Nick Vankemseke
//Variable Dictionary
//5th


Size: Boxes the objects to allow them to move.
P: Pointer to help allow object movement.
Q: See P.
I: Used solely to control loops.
Run: Gives the user the option to run the program again.
GrDriver: Does graphics stuff
GrMode: More graphics stuff
ErrorCode: LAst graphics stuff variable.
Vidseg: Points to the video screen.
Virseg: Contains the image in memeory to be flipped in.
Outfile: Opens the file stream.

