//Toni Whipple
//shell
//7th
//Mr. Baker

//Library Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//const section
const int ADD=10;
const int SUB=10;
const int MULT=10;
const int DIV=10;
const int MOD=10;

//variable section

void main()
{
cout<<"1+10"<<1+ADD<<endl;
cout<<"2+10"<<2+ADD<<endl;
cout<<"3+10"<<3+ADD<<endl;
cout<<"4+10"<<4+ADD<<endl;
cout<<"5+10"<<5+ADD<<endl;
cout<<"6+10"<<6+ADD<<endl;
cout<<"7+10"<<7+ADD<<endl;
cout<<"8+10"<<8+ADD<<endl;
cout<<"9+10"<<9+ADD<<endl;
cout<<"10+10"<<10+ADD<<endl;
getch();
clrscr();
cout<<"10-10"<<10-SUB<<endl;
cout<<"11-10"<<11-SUB<<endl;
cout<<"12-10"<<12-SUB<<endl;
cout<<"13-10"<<13-SUB<<endl;
cout<<"14-10"<<14-SUB<<endl;
cout<<"15-10"<<15-SUB<<endl;
cout<<"16-10"<<16-SUB<<endl;
cout<<"17-10"<<17-SUB<<endl;
cout<<"18-10"<<18-SUB<<endl;
cout<<"19-10"<<19-SUB<<endl;
cout<<"20-10"<<20-SUB<<endl;
getch();
clrscr();
cout<<"1*10"<<1*MULT<<endl;
cout<<"2*10"<<2*MULT<<endl;
cout<<"3*10"<<3*MULT<<endl;
cout<<"4*10"<<4*MULT<<endl;
cout<<"5*10"<<5*MULT<<endl;
cout<<"6*10"<<6*MULT<<endl;
cout<<"7*10"<<7*MULT<<endl;
cout<<"8*10"<<8*MULT<<endl;
cout<<"9*10"<<9*MULT<<endl;
cout<<"10*10"<<10*MULT<<endl;
getch();
clrscr();
cout<<"10/10"<<10/DIV<<endl;
cout<<"20/10"<<20/DIV<<endl;
cout<<"30/10"<<30/DIV<<endl;
cout<<"40/10"<<40/DIV<<endl;
cout<<"50/10"<<50/DIV<<endl;
cout<<"60/10"<<60/DIV<<endl;
cout<<"70/10"<<60/DIV<<endl;
cout<<"80/10"<<70/DIV<<endl;
cout<<"90/10"<<90/DIV<<endl;
cout<<"100/10"<<100/DIV<<endl;
getch();
clrscr();
cout<<"10%10"<<10%MOD<<endl;
cout<<"20%10"<<20%MOD<<endl;
cout<<"30%10"<<30%MOD<<endl;
cout<<"40%10"<<40%MOD<<endl;
cout<<"50%10"<<50%MOD<<endl;
cout<<"60%10"<<60%MOD<<endl;
cout<<"70%10"<<70%MOD<<endl;
cout<<"80%10"<<80%MOD<<endl;
cout<<"90%10"<<90%MOD<<endl;
cout<<"100%10"<<100%MOD<<endl;
getch();
clrscr();

}