//Toni Whipple
//shell
//7th
//Mr. Baker

//Library Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//const section
const int ADD=10;
const int SUB=10;
const int MULT=10;
const int DIV=10;
const int MOD=10;

//variable section

void main()
cout<<"1+10"<<1+ADD<<endl;
cout<<"2+10"<<2+ADD<<endl;
cout<<"3+10"<<3+ADD<<endl;
cout<<"4+10"<<4+ADD<<endl;
cout<<"5+10"<<5+ADD<<endl;
cout<<"6+10"<<6+ADD<<endl;
cout<<"7+10"<<7+ADD<<endl;
cout<<"8+10"<<8+ADD<<endl;
cout<<"9+10"<<9+ADD<<endl;
cout<<"10+10"<<10+Add<<endl;
getch();
clrscr();