//Toni Whipple
//shell
//7th
//Mr. Baker

//Library Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//const.section

//variable section
int Add=10;
int Sub=10;
int Mult=10;
int Div=10;
int Mod=10;
void main ()
{

cout<<"1+10"<<1+Add<<endl;
cout<<"2+10"<<2+Add<<endl;
cout<<"3+10"<<3+Add<<endl;
cout<<"4+10"<<4+Add<<endl;
cout<<"5+10"<<5+Add<<endl;
cout<<"6+10"<<6+Add<<endl;
cout<<"7+10"<<7+Add<<endl;
cout<<"8+10"<<8+Add<<endl;
cout<<"9+10"<<9+Add<<endl;
cout<<"10+10"<<10+Add<<endl;
getch();
clrscr();
cout<<"20-10"<<20-Sub<<endl;
cout<<"21-10"<<21-Sub<<endl;
cout<<"22-10"<<22-Sub<<endl;
cout<<"23-10"<<23-Sub<<endl;
cout<<"24-10"<<23-Sub<<endl;
cout<<"25-10"<<25-Sub<<endl;
cout<<"26-10"<<26-Sub<<endl;
cout<<"27-10"<<27-Sub<<endl;
cout<<"28-10"<<28-Sub<<endl;
cout<<"29-10"<<29-Sub<<endl;
cout<<"30-10"<<30-Sub<<endl;
getch();
clrscr();
cout<<"1*10"<<1*Mult<<endl;
cout<<"2*10"<<2*Mult<<endl;
cout<<"3*10"<<3*Mult<<endl;
cout<<"4*10"<<4*Mult<<endl;
cout<<"5*10"<<5*Mult<<endl;
cout<<"6*10"<<6*Mult<<endl;
cout<<"7*10"<<7*Mult<<endl;
cout<<"8*10"<<8*Mult<<endl;
cout<<"9*10"<<9*Mult<<endl;
cout<<"10*10"<<10*Mult<<endl;
getch();
clrscr();
cout<<"10/10"<<10/Div<<endl;
cout<<"20/10"<<20/Div<<endl;
cout<<"30/10"<<30/Div<<endl;
cout<<"40/10"<<40/Div<<endl;
cout<<"50/10"<<50/Div<<endl;
cout<<"60/10"<<60/Div<<endl;
cout<<"70/10"<<70/Div<<endl;
cout<<"80/10"<<80/Div<<endl;
cout<<"90/10"<<90/Div<<endl;
cout<<"100/10"<<100/Div<<endl;
getch();
clrscr();
cout<<"10%10"<<10%Mod<<endl;
cout<<"20%10"<<20%Mod<<endl;
cout<<"30%10"<<30%Mod<<endl;
cout<<"40%10"<<40%Mod<<endl;
cout<<"50%10"<<50%Mod<<endl;
cout<<"60%10"<<60%Mod<<endl;
cout<<"70%10"<<70%Mod<<endl;
cout<<"80%10"<<80%Mod<<endl;
cout<<"90%10"<<90%Mod<<endl;
cout<<"100%10"<<100%Mod<<endl;
getch();
clrscr();


}
