//Toni Whipple
//shell
//7th
//Mr. Baker

//Library Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//const.section

//variable section
apstring Name;
apstring Address;
apstring Phone;
void main()
{
Name="Toni Whipple";
Address="122 West Way Drive";
Phone="2144950456";

cout<<Name<<endl;
cout<<Address<<endl;
cout<<Phone<<endl;
getch();
clrscr();

 }
