//Toni Whipple
//prob#06
//7th block
//Mr. Baker

//liabrary
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>

//const section


//variable section
long Number;

void main()
{
clrscr();
cout<<"Please enter a number ex. 2"<<endl;
cin>>Number;
cout<<endl;

cout<<"Press enter to continue"<<endl;


getch();
clrscr();

if (Number%2<1)
 cout<<Number<<endl;

cout<<"Press enter to exit"<<endl;
getch();

}