//Toni Whipple
//prob 01
//block 7
//Mr. Baker

//liabrary section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>

//const section

//variable section

void main ()
{
cout<<"1+1="<<1+1<<endl;
cout<<"2+3="<<2+3<<endl;
cout<<"3+4="<<3+4<<endl;
cout<<"4+5="<<4+5<<endl;
cout<<"5+6="<<5+6<<endl;
cout<<"6+7="<<6+7<<endl;
cout<<"7+8="<<7+8<<endl;
cout<<"8+9="<<8+9<<endl;
cout<<"9+10="<<9+10<<endl;
cout<<"10+11="<<10+11<<endl;
getch();
clrscr();
cout<<"1-1="<<1-1<<endl;
cout<<"3-2="<<3-2<<endl;
cout<<"4-3="<<4-3<<endl;
cout<<"5-4="<<5-4<<endl;
cout<<"6-5="<<6-5<<endl;
cout<<"7-6="<<7-5<<endl;
cout<<"8-7="<<8-7<<endl;
cout<<"9-8="<<9-8<<endl;
cout<<"10-9="<<10-9<<endl;
cout<<"11-10="<<11-10<<endl;
getch();
clrscr();
cout<<"1*1="<<1*1<<endl;
cout<<"2*2="<<2*2<<endl;
cout<<"3*3="<<3*3<<endl;
cout<<"4*4="<<4*4<<endl;
cout<<"5*5="<<5*5<<endl;
cout<<"6*6="<<6*6<<endl;
cout<<"7*7="<<7*7<<endl;
cout<<"8*8="<<8*8<<endl;
cout<<"9*9="<<9*9<<endl;
cout<<"10*10="<<10*10<<endl;
getch();
clrscr();
cout<<"1/1"<<1/1<<endl;
cout<<"2/2"<<2/2<<endl;
cout<<"3/3"<<3/3<<endl;
cout<<"4/4"<<4/4<<endl;
cout<<"5/5"<<5/5<<endl;
cout<<"6/6"<<6/6<<endl;
cout<<"7/7"<<7/7<<endl;
cout<<"8/8"<<8/8<<endl;
cout<<"9/9"<<9/9<<endl;
cout<<"10/10"<<10/10<<endl;
getch();
clrscr();
cout<<"1%1"<<1%1<<endl;
cout<<"2%2"<<2%2<<endl;
cout<<"3%3"<<3%3<<endl;
cout<<"4%4"<<4%4<<endl;
cout<<"5%5"<<5%5<<endl;
cout<<"6%6"<<6%6<<endl;
cout<<"7%7"<<7%7<<endl;
cout<<"8%8"<<8%8<<endl;
cout<<"9%9"<<9%9<<endl;
cout<<"10%10"<<10%10<<endl;
getch();
clrscr();
}