#include <apstring.h>
typedef struct
{
apstring Name;
long Score;
} HSA;

typedef struct
{
apstring Name;
long Score;
} HS;



//Prototypes
void newscore(long);
int lv1();
int lv2();
int lv3();
int lv4();
int lv5();
int lv6();
int lv7();
int lv8();
int lv9();
int lv10();
int boss1();
int boss2();
int boss3();
int boss4();
void help();
void loose();
void highscore();