//Library Section
#include <apvector.h>
#include "shipdata.hpp"

//Constant Section

//Struct Section



//Global Variable Section
extern apvector <Star> Space;
extern Enemy Enemy10;
extern int Move,X,Y,MvScr,Z,Tmp,Ecolmn,Erow;
extern long Time;
extern bool Ekill;
extern Shot Temp;
extern Myship_dat MyShip;
extern apvector <Edat> EnemyShip;
extern long Score;
extern Bosses Boss;

//Prototypes