Program song;
(*El CHoDA
Baker 6th, *)

uses
    Crt;
procedure verse1;
begin
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('But only when thier green');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('but not when they are red');
end;
procedure chours;
begin
writeln ('he likes traffic lights');
writeln ('he likes traffic lights');
writeln ('he likes traffic lights');
writeln ('but only when thier green');
writeln ('he likes traffic lights');
writeln ('he likes traffic lights');
writeln ('he likes traffic lights');
writeln ('but not when they are red');
end;
procedure verse2;
begin
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('Eventhough my name''s not mertile');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('but only when they are the color of a turtle');
end;
procedure verse3;
begin
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('Eventhough my name is mortamier');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('I like traffic lights');
writeln ('Oh god');
end;
begin (*main*)
clrscr;
verse1;
readln;
chours;
readln;
verse2;
readln;
chours;
readln;
verse3;
readln;
End. (*main*)

