//Michael Crookston
//Problem #33I
//Due Date
//Period 6
//Mr. Baker
//Libraries Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
#include<fstream.h>
//Constants
//Prototypes
//Global Variables
ofstream Planets;
//Program
void main ()
{Planets.open("planets.txt");
Planets<<"Mercury"<<endl;
Planets<<"57.9"<<endl;
Planets<<"36.0"<<endl;
Planets<<"88 days"<<endl;
Planets<<"59 days"<<endl;
Planets<<"Near 0 degrees"<<endl;
Planets<<"7 degrees"<<endl;
Planets<<".206"<<endl;
Planets<<"4,880"<<endl;
Planets<<"3,032.4"<<endl;
Planets<<"Virtually None"<<endl;
Planets<<"0"<<endl;
Planets<<"0"<<endl;
Planets<<"Venus"<<endl;
Planets<<"108.2"<<endl;
Planets<<"67.24"<<endl;
Planets<<"224.7 days"<<endl;
Planets<<"243 days retrograde"<<endl;
Planets<<"3 degrees"<<endl;
Planets<<"3.4 degrees"<<endl;
Planets<<".007"<<endl;
Planets<<"12,100"<<endl;
Planets<<"7,519"<<endl;
Planets<<"Carbon dioxide"<<endl;
Planets<<"0"<<endl;
Planets<<"0"<<endl;
Planets<<"Earth"<<endl;
Planets<<"149.6"<<endl;
Planets<<"92.9"<<endl;
Planets<<"365.2 days"<<endl;
Planets<<"23 hr 56 min 4 sec"<<endl;
Planets<<"23 degrees 27'"<<endl;
Planets<<"0 degrees"<<endl;
Planets<<".017"<<endl;
Planets<<"12,756"<<endl;
Planets<<"7,926.2"<<endl;
Planets<<"Nitrogen, Oxygen"<<endl;
Planets<<"1"<<endl;
Planets<<"0"<<endl;
Planets<<"Mars"<<endl;
Planets<<"227.9"<<endl;
Planets<<"141.71"<<endl;
Planets<<"687 days"<<endl;
Planets<<"24 hr 37 min"<<endl;
Planets<<"25 degrees 12'"<<endl;
Planets<<"1.9 degrees"<<endl;
Planets<<".093"<<endl;
Planets<<"6,794"<<endl;
Planets<<"4,194"<<endl;
Planets<<"Carbon dioxide"<<endl;
Planets<<"2"<<endl;
Planets<<"0"<<endl;
Planets<<"Jupiter"<<endl;
Planets<<"778.3"<<endl;
Planets<<"483.88"<<endl;
Planets<<"11.86 yrs"<<endl;
Planets<<"9 hr 55 min 30 sec"<<endl;
Planets<<"3 degrees 5'"<<endl;
Planets<<"1.3 degrees"<<endl;
Planets<<".048"<<endl;
Planets<<"142,800"<<endl;
Planets<<"88,736"<<endl;
Planets<<"Hydrogen, Helium"<<endl;
Planets<<"16"<<endl;
Planets<<"1"<<endl;
Planets<<"Saturn"<<endl;
Planets<<"1,427"<<endl;
Planets<<"887.12"<<endl;
Planets<<"29.46 yrs"<<endl;
Planets<<"10 hr 40 min 24 sec"<<endl;
Planets<<"26 degrees 44'"<<endl;
Planets<<"2.5 degrees"<<endl;
Planets<<".056"<<endl;
Planets<<"120,660"<<endl;
Planets<<"74,978"<<endl;
Planets<<"Hydrogen, Helium"<<endl;
Planets<<"18+"<<endl;
Planets<<"1,000 (?)"<<endl;
Planets<<"Uranus"<<endl;
Planets<<"2,870"<<endl;
Planets<<"1,783.98"<<endl;
Planets<<"84 yrs"<<endl;
Planets<<"16.8 hr (?) retrograde"<<endl;
Planets<<"97 degrees 55'"<<endl;
Planets<<"0.8 degrees"<<endl;
Planets<<".047"<<endl;
Planets<<"51,810"<<endl;
Planets<<"32,193"<<endl;
Planets<<"Helium, Hydrogen, Methane"<<endl;
Planets<<"15"<<endl;
Planets<<"11"<<endl;
Planets<<"Neptune"<<endl;
Planets<<"4,497"<<endl;
Planets<<"2,796.46"<<endl;
Planets<<"165 yrs"<<endl;
Planets<<"16 hr 11 min (?)"<<endl;
Planets<<"28 degrees 48'"<<endl;
Planets<<"1.8 degrees"<<endl;
Planets<<".009"<<endl;
Planets<<"49,528"<<endl;
Planets<<"30,775"<<endl;
Planets<<"Hydrogen, Helium, Methane"<<endl;
Planets<<"8"<<endl;
Planets<<"4"<<endl;
Planets<<"Pluto"<<endl;
Planets<<"5,900"<<endl;
Planets<<"3,666"<<endl;
Planets<<"248 yrs"<<endl;
Planets<<"6 days 9 hr 18 mins retrograde"<<endl;
Planets<<"60 degrees (?)"<<endl;
Planets<<"17.2 degrees"<<endl;
Planets<<".254"<<endl;
Planets<<"2,290 (?)"<<endl;
Planets<<"1,423 (?)"<<endl;
Planets<<"None detected"<<endl;
Planets<<"1"<<endl;
Planets<<"?"<<endl;
Planets.close();
}
