//Michael Crookston
//Program Name
//Due Date
//Period 6
//Mr. Baker
//Libraries Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
//Constants

const int PROB1=1;
const int PROB2=2;
const int PROB3=3;
const int PROB4=4;
const int PROB5=5;
const int PROB6=6;
const int PROB7=7;
const int PROB8=8;
const int PROB9=9;
const int PROB0=10;

//Variables
//Program
void main ()
{
//Addition Section
clrscr();
cout<<PROB1<<"+"<<PROB1<<"="<<PROB1+PROB1<<endl;
cout<<PROB2<<"+"<<PROB1<<"="<<PROB2+PROB1<<endl;
cout<<PROB3<<"+"<<PROB1<<"="<<PROB3+PROB1<<endl;
cout<<PROB4<<"+"<<PROB1<<"="<<PROB4+PROB1<<endl;
cout<<PROB5<<"+"<<PROB1<<"="<<PROB5+PROB1<<endl;
cout<<PROB6<<"+"<<PROB1<<"="<<PROB6+PROB1<<endl;
cout<<PROB7<<"+"<<PROB1<<"="<<PROB7+PROB1<<endl;
cout<<PROB8<<"+"<<PROB1<<"="<<PROB8+PROB1<<endl;
cout<<PROB9<<"+"<<PROB1<<"="<<PROB9+PROB1<<endl;
cout<<PROB0<<"+"<<PROB1<<"="<<PROB0+PROB1<<endl;
cout<<"Press return for subtraction problems.";
getch();
//Subtraction Section
clrscr();
cout<<PROB1<<"-"<<PROB1<<"="<<PROB1-PROB1<<endl;
cout<<PROB2<<"-"<<PROB1<<"="<<PROB2-PROB1<<endl;
cout<<PROB3<<"-"<<PROB1<<"="<<PROB3-PROB1<<endl;
cout<<PROB4<<"-"<<PROB1<<"="<<PROB4-PROB1<<endl;
cout<<PROB5<<"-"<<PROB1<<"="<<PROB5-PROB1<<endl;
cout<<PROB6<<"-"<<PROB1<<"="<<PROB6-PROB1<<endl;
cout<<PROB7<<"-"<<PROB1<<"="<<PROB7-PROB1<<endl;
cout<<PROB8<<"-"<<PROB1<<"="<<PROB8-PROB1<<endl;
cout<<PROB9<<"-"<<PROB1<<"="<<PROB9-PROB1<<endl;
cout<<PROB0<<"-"<<PROB1<<"="<<PROB0-PROB1<<endl;
cout<<"Press return for multiplication problems.";
getch();
//Multiplication Problems
clrscr();
cout<<PROB1<<"*"<<PROB1<<"="<<PROB1*PROB1<<endl;
cout<<PROB2<<"*"<<PROB2<<"="<<PROB2*PROB2<<endl;
cout<<PROB3<<"*"<<PROB3<<"="<<PROB3*PROB3<<endl;
cout<<PROB4<<"*"<<PROB4<<"="<<PROB4*PROB4<<endl;
cout<<PROB5<<"*"<<PROB5<<"="<<PROB5*PROB5<<endl;
cout<<PROB6<<"*"<<PROB6<<"="<<PROB6*PROB6<<endl;
cout<<PROB7<<"*"<<PROB7<<"="<<PROB7*PROB7<<endl;
cout<<PROB8<<"*"<<PROB8<<"="<<PROB8*PROB8<<endl;
cout<<PROB9<<"*"<<PROB9<<"="<<PROB9*PROB9<<endl;
cout<<PROB0<<"*"<<PROB0<<"="<<PROB0*PROB0<<endl;
cout<<"Press return for division problems.";
getch();
//Division Problems
clrscr();
cout<<PROB1<<"/"<<PROB1<<"="<<PROB1/PROB1<<endl;
cout<<PROB2<<"/"<<PROB2<<"="<<PROB2/PROB2<<endl;
cout<<PROB3<<"/"<<PROB3<<"="<<PROB3/PROB3<<endl;
cout<<PROB4<<"/"<<PROB4<<"="<<PROB4/PROB4<<endl;
cout<<PROB5<<"/"<<PROB5<<"="<<PROB5/PROB5<<endl;
cout<<PROB6<<"/"<<PROB6<<"="<<PROB6/PROB6<<endl;
cout<<PROB7<<"/"<<PROB7<<"="<<PROB7/PROB7<<endl;
cout<<PROB8<<"/"<<PROB8<<"="<<PROB8/PROB8<<endl;
cout<<PROB9<<"/"<<PROB9<<"="<<PROB9/PROB9<<endl;
cout<<PROB0<<"/"<<PROB0<<"="<<PROB0/PROB0<<endl;
cout<<"Press return for mod problems.";
getch();
//Mod Problems
clrscr();
cout<<PROB1<<"%"<<PROB1<<"="<<PROB1%PROB1<<endl;
cout<<PROB2<<"%"<<PROB1<<"="<<PROB2%PROB1<<endl;
cout<<PROB3<<"%"<<PROB1<<"="<<PROB3%PROB1<<endl;
cout<<PROB4<<"%"<<PROB3<<"="<<PROB4%PROB3<<endl;
cout<<PROB5<<"%"<<PROB3<<"="<<PROB5%PROB3<<endl;
cout<<PROB6<<"%"<<PROB3<<"="<<PROB6%PROB3<<endl;
cout<<PROB7<<"%"<<PROB3<<"="<<PROB7%PROB3<<endl;
cout<<PROB8<<"%"<<PROB3<<"="<<PROB8%PROB3<<endl;
cout<<PROB9<<"%"<<PROB3<<"="<<PROB9%PROB3<<endl;
cout<<PROB0<<"%"<<PROB3<<"="<<PROB0%PROB3<<endl;
cout<<"Press return to leave the program.";
getch();




}
