//Michael Crookston
//Program Name
//Due Date
//Period 6
//Mr. Baker
//Libraries Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
//Constants
//Variables

int Prob1;
int Prob2;
int Prob3;
int Prob4;
int Prob5;
int Prob6;
int Prob7;
int Prob8;
int Prob9;
int Prob0;

//Program
void main ()
{
Prob1=1;
Prob2=2;
Prob3=3;
Prob4=4;
Prob5=5;
Prob6=6;
Prob7=7;
Prob8=8;
Prob9=9;
Prob0=10;
//Addition Section
clrscr();
cout<<Prob1<<"+"<<Prob1<<"="<<Prob1+Prob1<<endl;
cout<<Prob2<<"+"<<Prob1<<"="<<Prob2+Prob1<<endl;
cout<<Prob3<<"+"<<Prob1<<"="<<Prob3+Prob1<<endl;
cout<<Prob4<<"+"<<Prob1<<"="<<Prob4+Prob1<<endl;
cout<<Prob5<<"+"<<Prob1<<"="<<Prob5+Prob1<<endl;
cout<<Prob6<<"+"<<Prob1<<"="<<Prob6+Prob1<<endl;
cout<<Prob7<<"+"<<Prob1<<"="<<Prob7+Prob1<<endl;
cout<<Prob8<<"+"<<Prob1<<"="<<Prob8+Prob1<<endl;
cout<<Prob9<<"+"<<Prob1<<"="<<Prob9+Prob1<<endl;
cout<<Prob0<<"+"<<Prob1<<"="<<Prob0+Prob1<<endl;
cout<<"Press return for subtraction problems.";
getch();
//Subtraction Section
clrscr();
cout<<Prob1<<"-"<<Prob1<<"="<<Prob1-Prob1<<endl;
cout<<Prob2<<"-"<<Prob1<<"="<<Prob2-Prob1<<endl;
cout<<Prob3<<"-"<<Prob1<<"="<<Prob3-Prob1<<endl;
cout<<Prob4<<"-"<<Prob1<<"="<<Prob4-Prob1<<endl;
cout<<Prob5<<"-"<<Prob1<<"="<<Prob5-Prob1<<endl;
cout<<Prob6<<"-"<<Prob1<<"="<<Prob6-Prob1<<endl;
cout<<Prob7<<"-"<<Prob1<<"="<<Prob7-Prob1<<endl;
cout<<Prob8<<"-"<<Prob1<<"="<<Prob8-Prob1<<endl;
cout<<Prob9<<"-"<<Prob1<<"="<<Prob9-Prob1<<endl;
cout<<Prob0<<"-"<<Prob1<<"="<<Prob0-Prob1<<endl;
cout<<"Press return for multiplication problems.";
getch();
//Multiplication Problems
clrscr();
cout<<Prob1<<"*"<<Prob1<<"="<<Prob1*Prob1<<endl;
cout<<Prob2<<"*"<<Prob2<<"="<<Prob2*Prob2<<endl;
cout<<Prob3<<"*"<<Prob3<<"="<<Prob3*Prob3<<endl;
cout<<Prob4<<"*"<<Prob4<<"="<<Prob4*Prob4<<endl;
cout<<Prob5<<"*"<<Prob5<<"="<<Prob5*Prob5<<endl;
cout<<Prob6<<"*"<<Prob6<<"="<<Prob6*Prob6<<endl;
cout<<Prob7<<"*"<<Prob7<<"="<<Prob7*Prob7<<endl;
cout<<Prob8<<"*"<<Prob8<<"="<<Prob8*Prob8<<endl;
cout<<Prob9<<"*"<<Prob9<<"="<<Prob9*Prob9<<endl;
cout<<Prob0<<"*"<<Prob0<<"="<<Prob0*Prob0<<endl;
cout<<"Press return for division problems.";
getch();
//Division Problems
clrscr();
cout<<Prob1<<"/"<<Prob1<<"="<<Prob1/Prob1<<endl;
cout<<Prob2<<"/"<<Prob2<<"="<<Prob2/Prob2<<endl;
cout<<Prob3<<"/"<<Prob3<<"="<<Prob3/Prob3<<endl;
cout<<Prob4<<"/"<<Prob4<<"="<<Prob4/Prob4<<endl;
cout<<Prob5<<"/"<<Prob5<<"="<<Prob5/Prob5<<endl;
cout<<Prob6<<"/"<<Prob6<<"="<<Prob6/Prob6<<endl;
cout<<Prob7<<"/"<<Prob7<<"="<<Prob7/Prob7<<endl;
cout<<Prob8<<"/"<<Prob8<<"="<<Prob8/Prob8<<endl;
cout<<Prob9<<"/"<<Prob9<<"="<<Prob9/Prob9<<endl;
cout<<Prob0<<"/"<<Prob0<<"="<<Prob0/Prob0<<endl;
cout<<"Press return for mod problems.";
getch();
//Mod Problems
clrscr();
cout<<Prob1<<"%"<<Prob1<<"="<<Prob1%Prob1<<endl;
cout<<Prob2<<"%"<<Prob1<<"="<<Prob2%Prob1<<endl;
cout<<Prob3<<"%"<<Prob1<<"="<<Prob3%Prob1<<endl;
cout<<Prob4<<"%"<<Prob3<<"="<<Prob4%Prob3<<endl;
cout<<Prob5<<"%"<<Prob3<<"="<<Prob5%Prob3<<endl;
cout<<Prob6<<"%"<<Prob3<<"="<<Prob6%Prob3<<endl;
cout<<Prob7<<"%"<<Prob3<<"="<<Prob7%Prob3<<endl;
cout<<Prob8<<"%"<<Prob3<<"="<<Prob8%Prob3<<endl;
cout<<Prob9<<"%"<<Prob3<<"="<<Prob9%Prob3<<endl;
cout<<Prob0<<"%"<<Prob3<<"="<<Prob0%Prob3<<endl;
cout<<"Press return to leave the program.";
getch();




}
