//Michael Crookston
//Program Name
//Due Date
//Period 6
//Mr. Baker
//Libraries Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//Constants
//Variables
//Program
void main ()
{
 clrscr();
 //Addition Area
 cout<<"1+1="<<1+1<<endl;
 cout<<"53+6="<<53+6<<endl;
 cout<<"32+80="<<32+80<<endl;
 cout<<"12+7="<<12+7<<endl;
 cout<<"2+54="<<2+54<<endl;
 cout<<"12+16="<<12+16<<endl;
 cout<<"2+3="<<2+3<<endl;
 cout<<"5+55="<<5+55<<endl;
 cout<<"7+21="<<7+21<<endl;
 cout<<"55+55="<<55+55<<endl;
 cout<<"Press enter for subtraction formulas.";
 getch();
 //Subtraction Area
 clrscr();
 cout<<"1-1="<<1-1<<endl;
 cout<<"53-6="<<53-6<<endl;
 cout<<"32-80="<<32-80<<endl;
 cout<<"12-7="<<12-7<<endl;
 cout<<"2-54="<<2-54<<endl;
 cout<<"12-16="<<12-16<<endl;
 cout<<"2-3="<<2-3<<endl;
 cout<<"5-55="<<5-55<<endl;
 cout<<"7-21="<<7-21<<endl;
 cout<<"55-55="<<55-55<<endl;
 cout<<"Press enter for multiplication formulas.";
 getch();
 //Multiplication Area
	clrscr();
 cout<<"1*1="<<1*1<<endl;
 cout<<"53*6="<<53*6<<endl;
 cout<<"32*8="<<32*8<<endl;
 cout<<"12*7="<<12*7<<endl;
 cout<<"2*54="<<2*54<<endl;
 cout<<"12*16="<<12*16<<endl;
 cout<<"2*3="<<2*3<<endl;
 cout<<"5*55="<<5*55<<endl;
 cout<<"7*21="<<7*21<<endl;
 cout<<"5*5="<<5*5<<endl;
 cout<<"Press enter for division formulas.";
 getch();
 //Division Area
	clrscr();
 cout<<"1/1="<<1/1<<endl;
 cout<<"36/6="<<36/6<<endl;
 cout<<"32/8="<<32/8<<endl;
 cout<<"12/6="<<12/6<<endl;
 cout<<"54/2="<<54/2<<endl;
 cout<<"12/1="<<12/1<<endl;
 cout<<"2/2="<<2/2<<endl;
 cout<<"5/5="<<5/5<<endl;
 cout<<"21/7="<<21/7<<endl;
 cout<<"55/55="<<55/55<<endl;
 cout<<"Press enter for some remainders.";
 getch();
 //Mod Area
	clrscr();
 cout<<"1%1="<<1%1<<endl;
 cout<<"53%6="<<53%6<<endl;
 cout<<"32%80="<<32%80<<endl;
 cout<<"12%7="<<12%7<<endl;
 cout<<"2%54="<<2%54<<endl;
 cout<<"12%16="<<12%16<<endl;
 cout<<"2%3="<<2%3<<endl;
 cout<<"5%55="<<5%55<<endl;
 cout<<"7%21="<<7%21<<endl;
 cout<<"55%55="<<55%55<<endl;
 cout<<"Press enter to leave program.";
 getch();
}
