//Michael Crookston
//Prob#00
//8/16/00
//Period 6
//Mr. Baker
//Libraries Section
#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<apstring.h>
//Constants
const apstring MYNAME = "Michael Crookston";
const apstring MYADDRESS = "1301 Lombardy Way";
const apstring MYPHONE = "972-390-8721";
const apstring CONTINUE = "Press Return to continue.";
//Variables
//Program
void main ()
{
cout<<endl<<MYNAME<<endl<<MYADDRESS<<endl<<MYPHONE<<endl<<CONTINUE<<endl;
 getch();

}
